export const books = [
  {
    id: 1,
    title: "Interactive Mathematics: Grade 5",
    author: "Emily Thornton",
    cover: "/images/Graad 7 Musiek Cover.png",
    subject: "Mathematics",
    price: 29.99,
    description:
      "A comprehensive math textbook that makes learning fun and engaging for 5th graders.",
    type: "Physical",
    publisher: "Luminous Publishing",
    language: "English",
    paperback: "1105",
    isbn: "0312456789",
    dimension: "19 x 29cm",
    rating: 4.7,
    reviews: 120,
  },
  {
    id: 2,
    title: "STEM Projects for Young Learners",
    author: "Emily Thornton",
    cover: "/images/page.png",
    subject: "Science",
    price: 34.99,
    description:
      "Exciting hands-on projects that integrate science, technology, engineering, and math for primary school students.",
    type: "Physical",
    publisher: "Luminous Publishing",
    language: "English",
    paperback: "1200",
    isbn: "0312456790",
    dimension: "21 x 30cm",
    rating: 4.8,
    reviews: 85,
  },
  {
    id: 3,
    title: "Coding for Kids: Python Basics",
    author: "Michael Chen",
    cover: "/images/page.png",
    subject: "Computer Science",
    price: 27.99,
    description:
      "An introductory programming book that teaches children the fundamentals of Python in a fun, interactive way.",
    type: "Physical",
    publisher: "Luminous Publishing",
    language: "English",
    paperback: "950",
    isbn: "0312456791",
    dimension: "18 x 28cm",
    rating: 4.9,
    reviews: 200,
  },
  {
    id: 4,
    title: "Digital Literacy in the 21st Century",
    author: "Michael Chen",
    cover: "/images/page.png",
    subject: "Computer Science",
    price: 32.99,
    description:
      "A comprehensive guide to navigating the digital world, covering topics from online safety to critical thinking in the age of information.",
    type: "Physical",
    publisher: "Luminous Publishing",
    language: "English",
    paperback: "1050",
    isbn: "0312456792",
    dimension: "20 x 29cm",
    rating: 4.6,
    reviews: 150,
  },
];

export const authors = [
  {
    name: "Emily Thornton",
    image: "/images/woman.png",
    bio: "With over 20 years of experience in primary education, Emily Thornton brings a wealth of knowledge to her engaging and innovative teaching materials.",
    booksPublished: 12,
    classroomsImpacted: 5000,
    rating: 4.9,
    books: [books[0], books[1]],
  },
  {
    name: "Michael Chen",
    image: "/images/woman.png",
    bio: "A passionate advocate for STEM education, Michael Chen combines his background in computer science with his teaching experience to create cutting-edge resources.",
    booksPublished: 8,
    classroomsImpacted: 3500,
    rating: 4.8,
    books: [books[2], books[3]],
  },
];
