export const mainBooks = [
  {
    id: "main4",
    title: "Graad 4 Afrikaans Huistaal",
    grade: "Graad 4",
    cover: "/images/Graad4 - Graad 4.png",
    description:
      "Comprehensive Afrikaans Home Language book for Grade 4 students.",
    modules: ["1", "2"],
  },
  {
    id: "main5",
    title: "Graad 5 Afrikaans Huistaal",
    grade: "Graad 5",
    cover: "/images/main-Graad 5.png",
    description:
      "Comprehensive Afrikaans Home Language book for Grade 5 students.",
    modules: ["1", "2"],
  },
  {
    id: "main6",
    title: "Graad 6 Afrikaans Huistaal",
    grade: "Graad 6",
    cover: "/images/Graad4 - Graad 6.png",
    description:
      "Comprehensive Afrikaans Home Language book for Grade 6 students.",
    modules: ["1", "2", "3", "4"],
  },
  {
    id: "main7",
    title: "Graad 7 Afrikaans Huistaal",
    grade: "Graad 7",
    cover: "/images/Graad4 - Graad 7.png",
    description:
      "Comprehensive Afrikaans Home Language book for Grade 7 students.",
    modules: ["1", "2", "3", "4"],
  },
];

export const books = [
  {
    id: 1,
    title: "Graad 4",
    title2: "Skattejag",
    cycle: "Siklus 1",
    author: "Elna Pretorius",
    cover: "/images/Graad 4 Skattejag.png",
    images: [
      "/images/Skattejag 1.png",
      "/images/Skattejag 2.png",
      "/images/Skattejag 3.png",
    ],
    subject: "Module 1",
    grade: "Graad 4",
    number: "4",
    // price: 29.99,
    description:
      " 'n Interaktiewe werkboek wat leer pret vir graad 4 leerlinge maak.",
    type: "Physical",
    publisher: "Luminous Publishing",
    language: "Afrikaans",
    paperback: "1105",
    isbn: "0312456789",
    dimension: "19 x 29cm",
    rating: 4.7,
    reviews: 120,
    mainBookId: "main4",
  },
  {
    id: 2,
    title: "Sport",
    title2: "Sport",
    cycle: "Siklus 2",
    author: "Elna Pretorius",
    cover: "/images/Graad 4 Sport.png",
    images: [
      "/images/Sport 1.png",
      "/images/Sport 2.png",
      "/images/Sport 3.png",
    ],
    subject: "Module 2",
    grade: "Graad 4",
    number: "4",
    // price: 34.99,
    description:
      "Exciting hands-on projects that integrate science, technology, engineering, and math for primary school students.",
    type: "Physical",
    publisher: "Luminous Publishing",
    language: "Afrikaans",
    paperback: "1200",
    isbn: "0312456790",
    dimension: "21 x 30cm",
    rating: 4.8,
    reviews: 85,
    mainBookId: "main4",
  },
  {
    id: 3,
    title: "Graad 5 Ruimte",
    title2: "Ruimte",
    cycle: "Siklus 1",
    author: "Lindie Isherwood",
    cover: "/images/Graad 5 Ruimte.png",
    images: [
      "/images/Graad 5 Ruimte 1.png",
      "/images/Graad 5 Ruimte 2.png",
      "/images/Graad 5 Ruimte 3.png",
    ],
    subject: "Module 1",
    grade: "Graad 5",
    number: "5",
    // price: 27.99,
    description:
      "An introductory programming book that teaches children the fundamentals of Python in a fun, interactive way.",
    type: "Physical",
    publisher: "Luminous Publishing",
    language: "Afrikaans",
    paperback: "950",
    isbn: "0312456791",
    dimension: "18 x 28cm",
    rating: 4.9,
    reviews: 200,
    mainBookId: "main5",
  },
  {
    id: 4,
    title: "Safari",
    title2: "Safari",
    cycle: "Siklus 2",
    author: "Lindie Isherwood",
    cover: "/images/Graad 5 Safari.png",
    images: [
      "/images/Graad 5 Safari 1.png",
      "/images/Graad 5 Safari 2.png",
      "/images/Graad 5 Safari 3.png",
    ],
    subject: "Module 2",
    grade: "Graad 5",
    number: "5",
    // price: 32.99,
    description:
      "A comprehensive guide to navigating the digital world, covering topics from online safety to critical thinking in the age of information.",
    type: "Physical",
    publisher: "Luminous Publishing",
    language: "Afrikaans",
    paperback: "1050",
    isbn: "0312456792",
    dimension: "20 x 29cm",
    rating: 4.6,
    reviews: 150,
    mainBookId: "main5",
  },
  {
    id: 5,
    title: "Graad 6 Ruimte",
    title2: "Ruimte",
    cycle: "Module 1",
    author: "Sarah Johnson",
    cover: "/images/Graad 6 Ruimte.png",
    images: [
      "/images/Graad 6 Ruimte 1.png",
      "/images/Graad 6 Ruimte 2.png",
      "/images/Graad 6 Ruimte 3.png",
    ],
    subject: "Module 1",
    grade: "Graad 6",
    number: "6",
    // price: 25.99,
    description:
      "A collection of fun and educational science experiments designed for third-grade students.",
    type: "Physical",
    publisher: "Luminous Publishing",
    language: "Afrikaans",
    paperback: "880",
    isbn: "0312456793",
    dimension: "19 x 27cm",
    rating: 4.8,
    reviews: 95,
    mainBookId: "main6",
  },
  {
    id: 6,
    title: "Strokiesprente",
    title2: "Strokiesprente",
    cycle: "Module 2",
    author: "Sarah Johnson",
    cover: "/images/Graad 6 Strokiesprente.png",
    images: [
      "/images/Graad 6 Strokiesprente 1.png",
      "/images/Graad 6 Strokiesprente 2.png",
      "/images/Graad 6 Strokiesprente 3.png",
    ],
    subject: "Module 2",
    grade: "Graad 6",
    number: "6",
    // price: 25.99,
    description:
      "A collection of fun and educational science experiments designed for third-grade students.",
    type: "Physical",
    publisher: "Luminous Publishing",
    language: "Afrikaans",
    paperback: "880",
    isbn: "0312456793",
    dimension: "19 x 27cm",
    rating: 4.8,
    reviews: 95,
    mainBookId: "main6",
  },
  {
    id: 7,
    title: "Videospeletjies",
    title2: "Videospeletjies",
    cycle: "Module 3",
    author: "Sarah Johnson",
    cover: "/images/Graad 6 Videospeletjies.png",
    images: [
      "/images/Graad 6 Videospeletjies 1.png",
      "/images/Graad 6 Videospeletjies 2.png",
      "/images/Graad 6 Videospeletjies 3.png",
    ],
    subject: "Module 3",
    grade: "Graad 6",
    number: "6",
    // price: 25.99,
    description:
      "A collection of fun and educational science experiments designed for third-grade students.",
    type: "Physical",
    publisher: "Luminous Publishing",
    language: "Afrikaans",
    paperback: "880",
    isbn: "0312456793",
    dimension: "19 x 27cm",
    rating: 4.8,
    reviews: 95,
    mainBookId: "main6",
  },
  {
    id: 8,
    title: "Speurder / Spioen",
    title2: "Reis Local - Dis Lekker",
    cycle: "Module 4",
    author: "Sarah Johnson",
    cover: "/images/Graad 6 Speurder of Spioen.png",
    images: [
      "/images/Graad 6 Speurder of Spioen 1.png",
      "/images/Graad 6 Speurder of Spioen 2.png",
    ],
    subject: "Module 4",
    grade: "Graad 6",
    number: "6",
    // price: 25.99,
    description:
      "A collection of fun and educational science experiments designed for third-grade students.",
    type: "Physical",
    publisher: "Luminous Publishing",
    language: "Afrikaans",
    paperback: "880",
    isbn: "0312456793",
    dimension: "19 x 27cm",
    rating: 4.8,
    reviews: 95,
    mainBookId: "main6",
  },
  {
    id: 9,
    title: "Musiek",
    title2: "Musiek",
    cycle: "Module 1",
    author: "Sarah Johnson",
    cover: "/images/Graad 7 Musiek.png",
    images: [
      "/images/Graad 7 Musiek 1.png",
      "/images/Graad 7 Musiek 2.png",
      "/images/Graad 7 Musiek 3.png",
    ],
    subject: "Module 1",
    grade: "Graad 7",
    number: "7",
    // price: 25.99,
    description:
      "A collection of fun and educational science experiments designed for third-grade students.",
    type: "Physical",
    publisher: "Luminous Publishing",
    language: "Afrikaans",
    paperback: "880",
    isbn: "0312456793",
    dimension: "19 x 27cm",
    rating: 4.8,
    reviews: 95,
    mainBookId: "main7",
  },
  {
    id: 10,
    title: "Tegnologie",
    title2: "Tegnologie",
    cycle: "Module 2",
    author: "Sarah Johnson",
    cover: "/images/Graad 7 Tegnologie.png",
    images: [
      "/images/Graad 7 Tegnologie 1.png",
      "/images/Graad 7 Tegnologie 2.png",
      "/images/Graad 7 Tegnologie 3.png",
    ],
    subject: "Module 2",
    grade: "Graad 7",
    number: "7",
    // price: 25.99,
    description:
      "A collection of fun and educational science experiments designed for third-grade students.",
    type: "Physical",
    publisher: "Luminous Publishing",
    language: "Afrikaans",
    paperback: "880",
    isbn: "0312456793",
    dimension: "19 x 27cm",
    rating: 4.8,
    reviews: 95,
    mainBookId: "main7",
  },
  {
    id: 11,
    title: "Flieks",
    title2: "Flieks",
    cycle: "Module 3",
    author: "Sarah Johnson",
    cover: "/images/Graad 7 Flieks.png",
    images: [
      "/images/Graad 7 Flieks 1.png",
      "/images/Graad 7 Flieks 2.png",
      "/images/Graad 7 Flieks 3.png",
    ],
    subject: "Module 3",
    grade: "Graad 7",
    number: "7",
    // price: 25.99,
    description:
      "A collection of fun and educational science experiments designed for third-grade students.",
    type: "Physical",
    publisher: "Luminous Publishing",
    language: "Afrikaans",
    paperback: "880",
    isbn: "0312456793",
    dimension: "19 x 27cm",
    rating: 4.8,
    reviews: 95,
    mainBookId: "main7",
  },
  {
    id: 12,
    title: "Flieks",
    title2: "Tema",
    cycle: "Module 4",
    author: "Sarah Johnson",
    cover: "/images/Graad 7 Flieks.png",
    images: [
      "/images/Graad 7 Flieks 1.png",
      "/images/Graad 7 Flieks 2.png",
      "/images/Graad 7 Flieks 3.png",
    ],
    subject: "Module 3",
    grade: "Graad 7",
    number: "7",
    // price: 25.99,
    description:
      "A collection of fun and educational science experiments designed for third-grade students.",
    type: "Physical",
    publisher: "Luminous Publishing",
    language: "Afrikaans",
    paperback: "880",
    isbn: "0312456793",
    dimension: "19 x 27cm",
    rating: 4.8,
    reviews: 95,
    mainBookId: "main7",
  },
];

export const authors = [
  {
    name: "Elna Pretorius",
    image: "/images/Grade 6 Space Theme Module 1.png",
    bio: "With over 20 years of experience in primary education, Elna Pretorius brings a wealth of knowledge to her engaging and innovative teaching materials.",
    booksPublished: 12,
    classroomsImpacted: 5000,
    rating: 4.9,
    books: [books[0], books[1]],
  },
  {
    name: "Lindie Isherwood",
    image: "/images/Graad 7 Musiek Cover.png",
    bio: "A passionate advocate for STEM education, Lindie Isherwood combines his background in computer science with his teaching experience to create cutting-edge resources.",
    booksPublished: 8,
    classroomsImpacted: 3500,
    rating: 4.8,
    books: [books[2], books[3]],
  },
];
